Add clean egress
Signed-off-by: bzsuni <bingzhe.sun@daocloud.io>

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -281,6 +281,14 @@ deploy_project:
 				|| { KIND_CLUSTER_NAME=$(KIND_CLUSTER_NAME) ./scripts/debugCluster.sh $(KIND_KUBECONFIG) "detail"  $(E2E_NAMESPACE) ; exit 1 ; } ; \
 		exit 0
 
+.PHONY: uninstall_egress
+uninstall_egress: KIND_KUBECONFIG ?= $(E2E_KIND_KUBECONFIG_PATH)
+uninstall_egress: KIND_CLUSTER_NAME ?= $(E2E_KIND_CLUSTER_NAME)
+uninstall_egress:
+	@echo -e "\033[35m [helm uninstall egress] \033[0m"
+	helm uninstall project --wait --debug -n $(E2E_NAMESPACE) \
+	     --kubeconfig=$(KIND_KUBECONFIG)  || { $(KIND_CLUSTER_NAME) ./scripts/debugCluster.sh $(KIND_KUBECONFIG) "detail" $(E2E_NAMESPACE) ; exit 1 ; } ; \
+	kubectl --kubeconfig=$(KIND_KUBECONFIG) get all --all-namespaces  | grep -q "egressgateway"` && { echo "error: found egressgateway resources" ; exit 1 ; }
 
 # test kind is ok
 .PHONY: install_example_app
@@ -323,7 +331,7 @@ e2e_test:
 	@echo -e "\033[35mRun e2e testing on the cluster $(KIND_CLUSTER_NAME) \033[0m"
 	@echo -e "\033[35m label=$(E2E_GINKGO_LABELS)\n timeout=$(E2E_TIMEOUT) \n options=$(E2E_GINKGO_OPTION) \n egress_namespace=$(E2E_NAMESPACE) \033[0m"
 	@echo -e "\033[35m[STEP1]\033[0m check KUBECONFIG file path"; \
-		export KUBECONFIG=$(KIND_KUBECONFIG) ; [ -f "$(KIND_KUBECONFIG)" ] || { echo -e "error, does not exist KUBECONFIG $(E2E_KUBECONFIG)" ; exit 1 ; } ; \
+		export KUBECONFIG=$(KIND_KUBECONFIG) ; [ -f "$(KIND_KUBECONFIG)" ] || { echo -e "error, does not exist KUBECONFIG $(KIND_KUBECONFIG)" ; exit 1 ; } ; \
 		echo -e "success" ; \
 		echo -e "\033[35m[STEP2]\033[0m clean old e2e log file"; \
 		[ -f "$(E2E_LOG_FILE)" ] && rm -f "$(E2E_LOG_FILE)"; \
