ci: cherry pick
Signed-off-by: weizhou.lan@daocloud.io <weizhou.lan@daocloud.io>

diff --git a/.github/workflows/auto-release.yaml b/.github/workflows/auto-release.yaml
--- a/.github/workflows/auto-release.yaml
+++ b/.github/workflows/auto-release.yaml
@@ -76,6 +76,19 @@ jobs:
           branch: 'release-${{ env.RUN_YBranchName }}'
           sha: '${{ github.sha }}'
 
+      # for auto-cherrypick.yaml, create a label
+      - name: Create cherry-pick label
+        continue-on-error: true
+        run: |
+          echo ${{ secrets.WELAN_PAT }} | gh auth login --with-token
+          branchLabelName="${{ env.LABEL_PREFIX_CHERRYPICK }}release-${{ env.RUN_YBranchName }}"
+          mainLabelName="${{ env.LABEL_PREFIX_CHERRYPICK }}main"
+          echo "try to create label "
+          gh label create ${branchLabelName} --force
+          (( $? !=0 )) && echo "error, failed to create label ${branchLabelName}"
+          gh label create ${mainLabelName} --force
+          (( $? !=0 )) && echo "error, failed to create label ${mainLabelName}"
+
   build-release-image:
     needs: get-tag
     uses: ./.github/workflows/build-image-release.yaml
