Add support for 'squash and merge'

diff --git a/.github/workflows/auto-cherrypick.yaml b/.github/workflows/auto-cherrypick.yaml
--- a/.github/workflows/auto-cherrypick.yaml
+++ b/.github/workflows/auto-cherrypick.yaml
@@ -29,10 +29,14 @@ jobs:
           JSON: ${{ toJSON(github) }}
         run: |
           set -x
-          echo "============ print var ======== "
-              grep -Eio "Merge pull request #[0-9]+ " <<< "${JSON}" || true
-          PR_NUMBER=` grep -Eio "Merge pull request #[0-9]+ " <<< "${JSON}" | grep -Eo "[0-9]+" | uniq `
-              [ -n "${PR_NUMBER}" ] || { echo "no PR number, ignore" ; }
+          PR_NUMBER=$(grep -Eio "Merge pull request #[0-9]+ " <<< "${JSON}" | grep -Eo "[0-9]+" | uniq || true)
+          if [ -z "$PR_NUMBER" ]; then
+              PR_NUMBER=$(grep -oP '(?<=\(#)\d+(?=\))' <<< "${JSON}" | head -n 1 || true)
+          fi
+          if [ -z "$PR_NUMBER" ]; then
+              echo "No PR number, ignoring"
+              exit 0
+          fi
           PR_URL="https://github.com/${{ github.repository }}/pull/${PR_NUMBER}"
           ACTION_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
               grep '"username":'  <<< "${JSON}"
@@ -116,7 +120,7 @@ jobs:
                     if ! ERROR_MESSAGE=`git cherry-pick $COMMIT 2>&1` ; then
                           echo ">>>>>>>>>>>> fail when cherry pick $COMMIT to branch $BRANCH "
                           echo "$ERROR_MESSAGE"
-                          echo "---- failuire detail"
+                          echo "---- failure detail"
                           git status
                           git diff
                           echo "<<<<<<<<<<<<<"
@@ -163,7 +167,7 @@ jobs:
           echo "=========== check result ============"
           if [ "$FINAL_FAILURE" == "true" ] ; then
               # if failed to create issue or pr, fails
-              echo "error, failuire happened"
+              echo "error, failure happened"
           else
               echo "all done"
           fi
