Document version changes
Signed-off-by: tao.yang <tao.yang@daocloud.io>

diff --git a/.github/workflows/call-release-pages.yaml b/.github/workflows/call-release-pages.yaml
--- a/.github/workflows/call-release-pages.yaml
+++ b/.github/workflows/call-release-pages.yaml
@@ -4,6 +4,7 @@ env:
   MERGE_BRANCH: github_pages
   PR_LABEL: pr/robot_update
   PR_REVIEWER: lou-lan
+  DEST_DIRECTORY: 'docs'
   CHART_OUTPUT_PATH: output/chart/*
 
 on:
@@ -38,12 +39,14 @@ jobs:
         run: |
           pwd
           ls
-          if ${{ inputs.ref != '' }}; then
-              echo "call by workflow_call"
-              echo "RUN_REF=${{ inputs.ref }}" >> $GITHUB_ENV
-          elif ${{ github.event_name == 'workflow_dispatch' }} ; then
+          if ${{ github.event_name == 'workflow_dispatch' }}; then
               echo "call by workflow_dispatch"
-              echo "RUN_REF=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
+              echo "REF=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
+              echo "SUBMIT=true" >> $GITHUB_ENV
+          elif ${{ inputs.ref != '' }}; then
+              echo "call by workflow_call"
+              echo "REF=${{ inputs.ref }}" >> $GITHUB_ENV
+              echo "SUBMIT=${{ inputs.submit }}" >> $GITHUB_ENV
           else
               echo "unexpected event: ${{ github.event_name }}"
               exit 1
@@ -64,18 +67,9 @@ jobs:
           sudo chmod +x /usr/bin/yq
           yq &>/dev/null || exit 1
 
-      - name: Build Site and chart
+      - name: Build chart
         run: |
-          make build_doc
           make chart_package
-
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v3.1.1
-        with:
-          name: site_artifact
-          path: output/docs/site.tar.gz
-          retention-days: 0
-          if-no-files-found: error
 
       - name: Upload Artifact
         uses: actions/upload-artifact@v3.1.1
@@ -85,37 +79,78 @@ jobs:
           retention-days: 1
           if-no-files-found: error
 
-  create_pr:
-    name: Create PR
+  build_docs_and_charts:
+    name: build docs and charts
     needs: [package]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
         with:
-          ref: ${{ env.MERGE_BRANCH }}
+          ref: ${{ env.REF }}
+          fetch-depth: 0
 
-      ## doc
+      - name: Extract Version
+        id: extract
+        run: |
+          if ! grep -E "^[[:space:]]*v[0-9]+.[0-9]+.[0-9]+[[:space:]]*$" VERSION &>/dev/null ; then
+            echo "not a release version, skip generating doc."
+            cat VERSION
+            echo "SKIP_ALL_JOB=true" >> $GITHUB_ENV
+            exit 0
+          fi
+          # for example v0.6.1, the build's documentation version is v0.6
+          docVersion=` cat VERSION  | tr -d ' ' | tr -d '\n' | grep -Eo "v[0-9]+\.[0-9]+" `
+          if [ -n "${docVersion}" ]; then
+              echo "the version intercepted from the branch is: ${docVersion}"
+          else
+              echo "error, failed to get version." && exit 1
+          fi
+          git checkout -f ${{ env.MERGE_BRANCH }}
+          echo "Switch to the branch:${{ env.MERGE_BRANCH }} where the document is located"
+          ls
+          if [ -e "docs/${docVersion}" ]; then
+              echo "doc version:${docVersion} already exists, just update it."
+              echo "SET_LATEST=false" >> $GITHUB_ENV
+          else
+              echo "The doc version:${docVersion} does not exist yet, while generating the doc and set it to latest"
+              echo "SET_LATEST=true" >> $GITHUB_ENV
+          fi
+          echo "the doc version is: ${docVersion}"
+          echo "DOCS_TAG=${docVersion}" >> $GITHUB_ENV
+
+      - name: build doc
+        id: build_doc
+        # the v0.6.0-rc1 type does not require documentation to be built, but charts will still be built
+        if: ${{ env.SKIP_ALL_JOB != 'true' }}
+        run: |
+          git checkout ${{ env.REF }}
+          ls
+          echo "switch to the release version branch ${{ env.REF }}"
+          pip install mkdocs==1.5.2 mike==1.1.2 mkdocs-material mkdocs-static-i18n==1.0.2
+          git config user.email "robot@example.com"
+          git config user.name "robot"
+          cp ./docs/mkdocs.yml ./
+          if ${{ env.SET_LATEST == 'true' }} ;then
+              echo "generate doc version:${{ env.DOCS_TAG }} and set to latest."
+              mike deploy --rebase --prefix ${{ env.DEST_DIRECTORY }} -b ${{ env.MERGE_BRANCH }} --update-aliases ${{env.DOCS_TAG }} latest
+              mike set-default --prefix ${{ env.DEST_DIRECTORY }} -b ${{ env.MERGE_BRANCH }} latest
+          else
+              echo "the version:${{ env.DOCS_TAG }} of the doc does not need to be set to the latest."
+              mike deploy --rebase --prefix ${{ env.DEST_DIRECTORY }} -b ${{ env.MERGE_BRANCH }} ${{ env.DOCS_TAG }}
+          fi
+          rm -rf ./site
+          rm -rf ./mkdocs.yml
+          git checkout -f  ${{ env.MERGE_BRANCH }}
+          echo "Push a doc version: ${{ env.DOCS_TAG }} from branch: ${{ env.REF }}, update it to latest: ${{ env.SET_LATEST }} "
+
+      ## chart
       - name: Prepare
+        # the v0.6.0-rc1 type does not require documentation to be built, but charts will still be built
         run: |
           # prepare directory
           [ -d "docs/charts" ] && mv docs/charts charts
-          rm -rf docs
-          mkdir docs
 
-      - name: Download Artifact
-        uses: actions/download-artifact@v3.0.2
-        with:
-          name: site_artifact
-          path: docs
-
-      - name: Untar Doc
-        run: |
-          cd docs
-          tar -xzvf site.tar.gz
-          rm -f site.tar.gz
-
-      ## chart
       - name: Install Helm
         uses: azure/setup-helm@v3.5
 
@@ -135,13 +170,14 @@ jobs:
           helm repo index  ./charts  --url ${url}/charts
           mv ./charts/index.yaml ./index.yaml
 
-      # https://github.com/peter-evans/create-pull-request
+      # Allow auto-merge on general
       - name: Create Pull Request
         id: create_pr
+        if: ${{ env.SUBMIT == 'true' }}
         uses: peter-evans/create-pull-request@v5.0.2
         with:
-          title: "robot Update doc from ${{ needs.prepare_doc.outputs.ref }} to branch ${{ env.MERGE_BRANCH }} "
-          commit-message: "robot Update chart from ${{ needs.prepare_doc.outputs.ref }} to branch ${{ env.MERGE_BRANCH }} "
+          title: "robot update website or charts from ${{ env.REF }} to branch ${{ env.MERGE_BRANCH }} "
+          commit-message: "robot update website or charts from ${{ env.REF }} to branch ${{ env.MERGE_BRANCH }} "
           branch-suffix: timestamp
           branch: robot/update_doc
           delete-branch: true
@@ -149,4 +185,4 @@ jobs:
           signoff: true
           token: ${{ secrets.WELAN_PAT }}
           labels: ${{ env.PR_LABEL }}
-          reviewers: ${{ env.PR_REVIEWER }}
+          reviewers: ${{ env.PR_REVIWER }}
